import { router } from 'expo-router';
import React from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import Animated, { FadeInDown, FadeInUp } from 'react-native-reanimated';

import { AppHeader } from '@/components/app-header';
import { SectionHeading } from '@/components/section-heading';
import { Glyph } from '@/components/ui/glyph';
import { SurfaceCard } from '@/components/ui/surface-card';
import { COLORS, GUTTER, RADIUS, SHADOW } from '@/constants/theme';
import { useTasks } from '@/context/task-context';

export default function YouScreen() {
  const { profile, tasks, projects, areas, focusSessions, syncStatus, inboxCount } = useTasks();
  const completed = tasks.filter((task) => task.completed).length;
  const focusMinutes = focusSessions.reduce((total, session) => total + session.durationMinutes, 0);
  const longestSession = focusSessions.reduce((longest, session) => Math.max(longest, session.durationMinutes), 0);

  return (
    <View style={{ flex: 1, backgroundColor: COLORS.canvas }}>
      <ScrollView contentInsetAdjustmentBehavior="automatic" showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingHorizontal: GUTTER, paddingTop: 20, paddingBottom: 158, gap: 24 }}>
        <Animated.View entering={FadeInDown.duration(420)}><AppHeader eyebrow="Your space" title="A system that fits real life." subtitle="Private by default, useful enough to return to." profileInitial={profile.displayName.slice(0, 1).toUpperCase()} actionIcon="settings" onAction={() => router.push('/settings')} /></Animated.View>

        <Animated.View entering={FadeInUp.delay(60).duration(430)} style={{ backgroundColor: COLORS.contrast, borderRadius: RADIUS.large, padding: 19, gap: 16, boxShadow: SHADOW }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 13 }}><View style={{ width: 55, height: 55, borderRadius: 18, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: COLORS.contrastText, fontSize: 22, fontWeight: '900' }}>{profile.displayName.slice(0, 1).toUpperCase()}</Text></View><View style={{ flex: 1, gap: 4 }}><Text selectable style={{ color: COLORS.contrastText, fontSize: 20, fontWeight: '900' }}>{profile.displayName}</Text><Text style={{ color: COLORS.contrastMuted, fontSize: 12, fontWeight: '700' }}>{profile.email ?? 'Guest workspace'} · {syncStatus === 'synced' ? 'synced' : 'saved locally'}</Text></View><Glyph name="chevron" size={16} color={COLORS.contrastMuted} /></View><View style={{ height: 1, backgroundColor: COLORS.contrastLine }} /><Text style={{ color: COLORS.primary, fontSize: 14, lineHeight: 20, fontWeight: '800' }}>“{profile.focusIntent}.”</Text><Pressable onPress={() => router.push('/settings')} style={({ pressed }) => [{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, pressed && { opacity: 0.6 }]}><Text style={{ color: COLORS.contrastMuted, fontSize: 12, fontWeight: '800' }}>Shape your preferences</Text><Glyph name="arrow" size={15} color={COLORS.primary} /></Pressable></Animated.View>

        <View style={{ gap: 12 }}><SectionHeading title="Your signals" subtitle="Useful data, without the guilt" /><View style={{ flexDirection: 'row', gap: 9 }}>{[{ value: String(completed), label: 'completed', icon: 'check' as const }, { value: `${focusMinutes}m`, label: 'focused', icon: 'clock' as const }, { value: String(inboxCount), label: 'in inbox', icon: 'inbox' as const }].map((stat) => <SurfaceCard key={stat.label} style={{ flex: 1, padding: 14, gap: 10 }}><Glyph name={stat.icon} size={15} color={COLORS.ink} /><Text selectable style={{ color: COLORS.ink, fontSize: 21, fontWeight: '900', fontVariant: ['tabular-nums'] }}>{stat.value}</Text><Text style={{ color: COLORS.muted, fontSize: 11, lineHeight: 14, fontWeight: '800' }}>{stat.label}</Text></SurfaceCard>)}</View></View>

        <View style={{ gap: 12 }}><SectionHeading title="Focus history" subtitle={`${focusSessions.length} sessions · longest ${longestSession || 0}m`} action="Start focus" onAction={() => router.push('/focus')} /><SurfaceCard style={{ paddingHorizontal: 16 }}>{focusSessions.length ? focusSessions.slice(-4).reverse().map((session) => { const task = tasks.find((item) => item.id === session.taskId); return <View key={session.id} style={{ minHeight: 57, flexDirection: 'row', alignItems: 'center', gap: 11, borderBottomWidth: 1, borderBottomColor: COLORS.line }}><View style={{ width: 29, height: 29, borderRadius: 10, backgroundColor: COLORS.primarySoft, alignItems: 'center', justifyContent: 'center' }}><Glyph name="clock" size={14} color={COLORS.primary} /></View><View style={{ flex: 1, gap: 3 }}><Text style={{ color: COLORS.ink, fontSize: 13, fontWeight: '800' }}>{task?.title ?? 'Open focus session'}</Text><Text style={{ color: COLORS.muted, fontSize: 11, fontWeight: '700' }}>{new Date(session.startedAt).toLocaleDateString([], { month: 'short', day: 'numeric' })}</Text></View><Text style={{ color: COLORS.ink, fontSize: 12, fontWeight: '900', fontVariant: ['tabular-nums'] }}>{session.durationMinutes}m</Text></View> }) : <View style={{ alignItems: 'center', padding: 22, gap: 7 }}><Text style={{ color: COLORS.ink, fontSize: 14, fontWeight: '900' }}>No focus history yet.</Text><Text style={{ color: COLORS.muted, fontSize: 12, fontWeight: '600' }}>Start a quiet session when you are ready.</Text></View>}</SurfaceCard></View>

        <View style={{ gap: 12 }}><SectionHeading title="Weekly reset" subtitle="Close loops before they become noise" /><Pressable onPress={() => router.push('/review')} style={({ pressed }) => [{ backgroundColor: COLORS.primarySoft, borderRadius: RADIUS.medium, padding: 17, flexDirection: 'row', alignItems: 'center', gap: 12 }, pressed && { opacity: 0.72 }]}><View style={{ width: 35, height: 35, borderRadius: 12, backgroundColor: COLORS.contrast, alignItems: 'center', justifyContent: 'center' }}><Glyph name="spark" size={17} color={COLORS.primary} /></View><View style={{ flex: 1, gap: 4 }}><Text style={{ color: COLORS.ink, fontSize: 14, fontWeight: '900' }}>Review what had your attention</Text><Text style={{ color: COLORS.muted, fontSize: 12, fontWeight: '600' }}>A five-minute reset, no score attached.</Text></View><Glyph name="chevron" size={16} color={COLORS.ink} /></Pressable></View>

        <View style={{ gap: 12 }}><SectionHeading title="Life areas" subtitle="Your attention has more than one home" /><SurfaceCard style={{ paddingHorizontal: 16 }}>{areas.filter((area) => !area.archivedAt).map((area) => <View key={area.id} style={{ minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1, borderBottomColor: COLORS.line }}><View style={{ width: 30, height: 30, borderRadius: 10, backgroundColor: `${area.color}18`, alignItems: 'center', justifyContent: 'center' }}><Glyph name={area.icon === 'briefcase' ? 'briefcase' : area.icon === 'heart' ? 'heart' : 'spark'} size={15} color={area.color} /></View><Text style={{ flex: 1, color: COLORS.ink, fontSize: 13, fontWeight: '800' }}>{area.name}</Text><Text style={{ color: COLORS.muted, fontSize: 11, fontWeight: '700' }}>{projects.filter((project) => project.areaId === area.id && project.status === 'active').length} projects</Text></View>)}</SurfaceCard></View>

        <Pressable onPress={() => router.push('/settings')} style={({ pressed }) => [{ minHeight: 55, backgroundColor: COLORS.surface, borderRadius: RADIUS.medium, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 12, boxShadow: SHADOW }, pressed && { opacity: 0.65 }]}><Glyph name="settings" size={18} color={COLORS.muted} /><Text style={{ flex: 1, color: COLORS.ink, fontSize: 14, fontWeight: '800' }}>Settings & privacy</Text><Glyph name="chevron" size={16} color={COLORS.softMuted} /></Pressable>
      </ScrollView>
    </View>
  );
}
